//This is when ran locally

#GET request returns "hello big world"
GET http://localhost:3000/


#GET request that returns all contacts 
GET http://localhost:3000/contacts


#GET request that returns a single contact
GET http://localhost:3000/contacts/662ae1e140313acb7032afe8

//This is on a live site

#GET request returns "hello big world"
GET https://cse321-w1-project.onrender.com/


#GET request that returns all contacts 
GET https://cse321-w1-project.onrender.com/contacts


#GET request that returns a single contact
GET https://cse321-w1-project.onrender.com/contacts/662ae1e140313acb7032afe8